version: 2
jobs:
  # Define the build step to check if build is possible
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.9

    steps:
      # Fetch the repo
      - checkout

      # Used in optimization
      - restore_cache:
          key: ec1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      # Install all dependencies
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt

      # Used in optimization
      - save_cache:
          key: ec1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv

  # Define the test step
  test:
    working_directory: ~/repo

    docker:
      - image: circleci/python:3.9

    steps:
      # Fetch the repo
      - checkout

      # Used in optimization
      - restore_cache:
          key: ec1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      # Install all dependencies
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt

      # Check if code style is ok
      - run:
          name: Run style checking
          command: flake8 --exclude=env* --statistics

      # Run the unit tests
      - run:
          name: Running tests
          command: pytest -v

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

      - test:
          # Only run the tests if the build step succeeded
          requires:
            - build
